import { NextResponse } from 'next/server';
import { getPlaylistMetadata, getUserProfile, PlaylistMetadata, UserProfile } from '@/lib/spotify';
import { query } from '@/lib/db';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  try {
    // 1. Check database for flags and owner
    const dbResult = await query('SELECT playlist_name, is_spotify_generated, playlist_owner_spotify_id, playlist_owner_display_name, playlist_art_uri FROM playlists WHERE playlist_spotify_id = @id', { id });
    
    if (dbResult.recordset.length === 0) {
      return NextResponse.json({ error: 'Playlist not found in database' }, { status: 404 });
    }

    const { playlist_name, is_spotify_generated, playlist_owner_spotify_id, playlist_owner_display_name, playlist_art_uri } = dbResult.recordset[0];

    // 2. Fetch Owner Profile (always needed)
    let userProfile = undefined;
    try {
      if (playlist_owner_spotify_id) {
        userProfile = await getUserProfile(playlist_owner_spotify_id);
      }
    } catch (e) {
      console.warn('Failed to fetch user profile:', e);
    }

    // 2. Handle Spotify Generated Playlists
    if (is_spotify_generated) {
      // Return placeholder metadata
      const placeholderMetadata: PlaylistMetadata = {
        name: playlist_name, // The frontend might override this with the DB name if available, but for now this is a safe fallback
        owner: {
          display_name: userProfile?.display_name || 'Spotify',
          id: userProfile?.id || 'spotify',
          images: userProfile?.images || [],
          external_urls: userProfile?.external_urls || { spotify: 'https://open.spotify.com/user/spotify' }
        },
        images: [], // Frontend will handle empty images with a placeholder
        description: 'This playlist is generated by Spotify.'
      };
      return NextResponse.json(placeholderMetadata);
    }

    // 3. Fetch Real Metadata for user playlists
    const metadata: PlaylistMetadata = {
      name: playlist_name,
      owner: {
        display_name: userProfile?.display_name || 'Unknown User',
        id: userProfile?.id || 'unknown',
        images: userProfile?.images || [],
        external_urls: userProfile?.external_urls || { spotify: `https://open.spotify.com/user/${userProfile?.id || 'unknown'}` }
      },
      images: playlist_art_uri ? [{ url: playlist_art_uri, height: 300, width: 300 }] : [],
      description: ''
    };
    return NextResponse.json(metadata);
  } catch (error) {
    console.error('Error fetching playlist metadata:', error);
    return NextResponse.json({ error: 'Failed to fetch playlist metadata' }, { status: 500 });
  }
}
