import { NextResponse } from 'next/server';
import { getPlaylistMetadata, getUserProfile, PlaylistMetadata } from '@/lib/spotify';
import { query } from '@/lib/db';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  try {
    // 1. Check database for flags and owner
    const dbResult = await query('SELECT is_spotify_generated, playlist_owner_spotify_id FROM playlists WHERE playlist_spotify_id = @id', { id });
    
    if (dbResult.recordset.length === 0) {
      return NextResponse.json({ error: 'Playlist not found in database' }, { status: 404 });
    }

    const { is_spotify_generated, playlist_owner_spotify_id } = dbResult.recordset[0];

    // 2. Fetch Owner Profile (always needed)
    let userProfile = undefined;
    try {
      if (playlist_owner_spotify_id) {
        userProfile = await getUserProfile(playlist_owner_spotify_id);
      }
    } catch (e) {
      console.warn('Failed to fetch user profile:', e);
    }

    // 3. Handle Spotify Generated Playlists
    if (is_spotify_generated) {
      // Return placeholder metadata
      const placeholderMetadata: PlaylistMetadata = {
        name: 'Spotify Generated Playlist', // The frontend might override this with the DB name if available, but for now this is a safe fallback
        owner: {
          display_name: userProfile?.display_name || 'Spotify',
          id: playlist_owner_spotify_id || 'spotify'
        },
        images: [], // Frontend will handle empty images with a placeholder
        description: 'This playlist is generated by Spotify.',
        userProfile
      };
      return NextResponse.json(placeholderMetadata);
    }

    // 4. Fetch Real Metadata for user playlists
    try {
      const metadata = await getPlaylistMetadata(id);
      return NextResponse.json({
        ...metadata,
        userProfile
      });
    } catch (error) {
      console.warn('Failed to fetch playlist metadata from Spotify, falling back to placeholder:', error);
       // Fallback if Spotify API fails (e.g. 404 for private playlists)
       const fallbackMetadata: PlaylistMetadata = {
        name: 'Playlist',
        owner: {
          display_name: userProfile?.display_name || 'Unknown User',
          id: playlist_owner_spotify_id || 'unknown'
        },
        images: [],
        description: '',
        userProfile
      };
      return NextResponse.json(fallbackMetadata);
    }

  } catch (error) {
    console.error('Error fetching playlist metadata:', error);
    return NextResponse.json({ error: 'Failed to fetch playlist metadata' }, { status: 500 });
  }
}
